services:
  qr-nele-till:
    image: git.orfel.de/jannik/qr-nele-till:latest
    container_name: qr-nele-till
    restart: unless-stopped
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
