services:
  clink:
    build:
      context: .
      dockerfile: Dockerfile
    image: clink:latest
    container_name: clink
    restart: unless-stopped
    environment:
      - BIND=0.0.0.0
      - HOST=0.0.0.0
    ports:
      - "127.0.0.1:5234:8080"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/clink:/srv/clink
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
