services:
  clink:
    image: crueter/clink:latest
    container_name: clink
    restart: unless-stopped
    ports:
      - "127.0.0.1:5234:3000"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/clink:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
