services:
  linus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPO_URL: https://github.com/H4f3rk3ks/lsound-website1326.git
        BRANCH: main
    image: linus:latest
    container_name: linus
    restart: unless-stopped
    ports:
      - "127.0.0.1:1326:80"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/linus:/data
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
