services:
  archivebox:
    image: archivebox/archivebox:latest
    container_name: archivebox
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/archivebox:/data
    environment:
      - ALLOWED_HOSTS=*
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
