services:
  baserow:
    image: baserow/baserow:latest
    container_name: baserow
    restart: unless-stopped
    ports:
      - "127.0.0.1:2273:80"
    environment:
      BASEROW_PUBLIC_URL: https://br.orfel.de
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_PORT: "5432"
      SECRET_KEY: ${SECRET_KEY}
      BASEROW_ADMIN_EMAIL: ${EMAIL}
      BASEROW_ADMIN_PASSWORD: ${PASSWORD}
      BASEROW_CADDY_ADDRESSES: ":80"
      # --- Performance tuning ---
      BASEROW_AMOUNT_OF_WORKERS: "1"
      BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION: "false"
      BASEROW_AMOUNT_OF_GUNICORN_WORKERS: "2"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/baserow:/baserow/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
