services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    ports:
      - "127.0.0.1:33:7912"
    environment:
      SPOOLMAN_DB_URL: ${SPOOLMAN_DB_URL}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/spoolman:/home/app/.local/share/spoolman
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
