services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    ports:
      - "127.0.0.1:33:8000"
    environment:
      SPOOLMAN_DB_TYPE: postgres
      SPOOLMAN_DB_HOST: postgres
      SPOOLMAN_DB_PORT: 5432
      SPOOLMAN_DB_NAME: ${DB_NAME}
      SPOOLMAN_DB_USERNAME: ${DB_USER}
      SPOOLMAN_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/spoolman:/home/app/.local/share/spoolman
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
