services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    restart: unless-stopped
    command: server standalone
    ports:
      - "127.0.0.1:5378:8080"
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/${DB_NAME}
            driverClassName: org.postgresql.Driver
            username: ${DB_USER}
            password: ${DB_PASSWORD}
      KESTRA_SECRET_KEY: ${KESTRA_SECRET_KEY}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/kestra:/app/storage
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
