services:
  cbrn-frontend:
    image: git.orfel.de/jannik/cbrn-frontend:latest
    container_name: cbrn-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:2276:80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    networks:
      - jannik-cloud-net

  cbrn-backend:
    image: git.orfel.de/jannik/cbrn-backend:latest
    container_name: cbrn-backend
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
