services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "7277:80"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      DOMAIN: https://pw.orfel.de
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: "true"
      WEBSOCKET_ENABLED: "true"
      SMTP_HOST: ""
      SMTP_FROM: ${EMAIL}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/vaultwarden:/data
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
