services:
  deezer:
    image: kmille2/deezer-downloader:latest
    container_name: deezer
    restart: unless-stopped
    ports:
      - "127.0.0.1:673:5000"
    environment:
      DEEZER_ARL: ${DEEZER_ARL}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/deezer/downloads:/downloads
      - /mnt/Jannik-Cloud-Volume-01/deezer/config:/config
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
