services:
  erkw:
    image: git.orfel.de/jannik/erkw:latest # Update: Modul 2 Folien und Uebungen 1 & 2 repariert (Offset- und Asset-Korrektur)
    pull_policy: always
    container_name: erkw
    restart: unless-stopped
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/erkw/.htpasswd:/etc/nginx/.htpasswd:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
