services:
  quizmaster:
    image: nymanjens/quizmaster:latest
    container_name: quizmaster
    command: ["bin/server"]
    restart: unless-stopped
    environment:
      - BIND=0.0.0.0
      - HOST=0.0.0.0
    ports:
      - "127.0.0.1:5235:9000"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/quizmaster/quiz:/app/conf/quiz
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
