services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    ports:
      - "127.0.0.1:556:4000"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      LITELLM_MASTER_KEY: ${MASTER_KEY}
      LITELLM_SALT_KEY: ${SALT_KEY}
      UI_USERNAME: ${USERNAME}
      UI_PASSWORD: ${PASSWORD}
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/litellm:/app/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
