services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "127.0.0.1:7678:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/Jannik-Cloud-Volume-01/portainer:/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
