services:
  iobroker:
    image: buanet/iobroker:latest
    container_name: iobroker
    restart: unless-stopped
    ports:
      - "127.0.0.1:46:8081"
    environment:
      IOB_ADMINPORT: 8081
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/iobroker:/opt/iobroker
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
