services:
  bit:
    image: sjdonado/bit:latest
    container_name: bit
    restart: unless-stopped
    environment:
      - ADMIN_NAME=admin
      - ADMIN_API_KEY=bit-admin-secret-key-123
      - APP_URL=https://bit.orfel.de
      - ENV=production
    ports:
      - "127.0.0.1:5233:4000"
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/bit:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
