services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    networks:
      - jannik-cloud-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    environment:
      ACME_AGREE: "true"
      EMAIL: "${EMAIL}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local

networks:
  jannik-cloud-net:
    external: true
