services:
  mc-survival-wiki-db:
    image: postgres:15
    container_name: mc_survival_wiki_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: wiki_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mc_wiki
    volumes:
      - /mnt/Jannik-Cloud-Volume-01/mc-survival-wiki/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiki_user -d mc_wiki"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mc-survival-wiki-net

  mc-survival-wiki-web:
    build: /mnt/Jannik-Cloud-Volume-01/mc-survival-wiki/app
    container_name: mc_survival_wiki_web
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://wiki_user:${DB_PASSWORD}@mc-survival-wiki-db:5432/mc_wiki?schema=public"
      BETTER_AUTH_SECRET: "${AUTH_SECRET}"
      BETTER_AUTH_URL: "https://mc-survival-wiki.orfel.de"
    ports:
      - "127.0.0.1:6294:3000"
    depends_on:
      mc-survival-wiki-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    networks:
      - mc-survival-wiki-net
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
  mc-survival-wiki-net:
