services:
  webhook:
    image: almir/webhook:latest
    container_name: webhook
    restart: unless-stopped
    ports:
      - "127.0.0.1:9500:9000"
    command: [ "-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload" ]
    environment:
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    volumes:
      - ./hooks.json:/etc/webhook/hooks.json:ro
      - ./scripts:/etc/webhook/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/Jannik-Cloud:/opt/Jannik-Cloud:ro
      - /usr/bin/docker:/usr/bin/docker:ro
    networks:
      - jannik-cloud-net

networks:
  jannik-cloud-net:
    external: true
